version: "3.9"
services:
  app:
    container_name: app
    build: .
    ports:
      - "8003:3000"
      - "5004:5555"
      - "5556:5556"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.4
    ports:
      - "8004:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
