version: "3.9"
services:
  app:
    build: .
    ports:
      - "8003:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:14.4
    ports:
      - "8004:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker